### PR TITLE
Add opcodes to "Lists" documentation

### PR DESCRIPTION
**Pull request by shemnon**
Add a summary of used, pending, and proposed opcodes for the EVM. 
Also adds a list describing each 16 opcode block,

### CODE REVIEW

**Comment by shemnon** [comment]
@SamWilsn @lightclient can I get a review on this?

**Review by petertdavies — APPROVED** [review]
I think this is a perfectly reasonable. In the long term it would be nice to auto generate from the specs, but we are nowhere near that at the moment.

**Comment by shemnon** [comment]
`opcodes.md` and `opcode-blocks.md` could be auto generated from the spec and other pages, but I think the more uniquely useful page is the `pending-opcodes.md`, where opcodes that are targeting the next release are laid out, and it could serve as an aid in final selection of opcode numbers.

**Review by chfast — APPROVED** [review]
We have applied changes in https://github.com/ethereum/evmone/pull/665 and we are happy with it.

I'm only slightly concerned that there is some duplication of information in these 3 tables.

**Pull request merged**
