### PR TITLE
Update Shanghai and add Cancun

### PR DESCRIPTION
**Pull request by timbeiko**
This reflects the decisions made on [ACD151](https://github.com/ethereum/pm/issues/675), namely: 

- Including the EOF EIPs into Shanghai (may be removed if not ready by January)
- Including EIP-4844 in a newly specified Cancun upgrade, set to follow Shanghai (naming follows [devcon locations chronologically](https://archive.devcon.org/archive/))
- Moving previously CFI'd EIPs to the Cancun spec to discuss them further in future calls. 
   - Note: CFI'd should probably be moved outside of specific upgrade specs, but wanted to minimize changes in this specific PR, so just stuck to existing pattern.

### CODE REVIEW

**Review by djrtwo — APPROVED** [review]

**Comment by holgerd77** [comment]
LGTM

**Comment by holgerd77** [comment]
Do we want an entry in the table from the root README as well? 🤔

**Comment by holgerd77** [comment]
(so: for Cancun)

**Comment by timbeiko** [comment]
Good catch, @holgerd77 ! Quickly added it in a follow up commit: https://github.com/ethereum/execution-specs/commit/ccf47a3a61035ce68bdd77733b12e5704a25f40d

**Pull request merged**
