### PR TITLE
Remove EOF from Shanghai Spec

### PR DESCRIPTION
**Pull request by timbeiko**
Decided on ACD#152

### CODE REVIEW

**Comment by yperbasis** [comment]
Shall we move them to Cancun CFI instead?

**Comment by timbeiko** [comment]
@shemnon asked the same thing in the R&D discord. Happy to make that change if Geth + Nethermind also +1 :-)

**Comment by holgerd77** [comment]
Would also support moving to Cancun CFI, I guess this will help that the topic stays on the table in a sufficient manner and also helps to serve as a reminder to continuously evolve thoughts on the topic and have necessary in-between discussions and decisions so that we hopefully get to a consistent and holistic plan on this incuding some long-term thinking throughout the months without the need for some last-minute rush where things run the risk to fall under the table.

**Comment by timbeiko** [comment]
Merged as-is because other changes are blocked on it. Added an agenda item about Cancun CFI to the next ACD (https://github.com/ethereum/pm/issues/704) given we couldn't get everyone to agree async here.

**Pull request merged**
