### PR TITLE
Replace uncle with ommer (closes #393)

### LINKED ISSUE #393: Replace `uncle` with `ommer` in spec
`ommer` is the preferred terminology.

At the time of writing, these files use `uncle` instead of `ommer`:
 - https://github.com/ethereum/execution-specs/blob/8e8379de0d61b2b76265173108fabae7111e03bf/src/ethereum/frontier/spec.py#L58
 - https://github.com/ethereum/execution-specs/blob/8e8379de0d61b2b76265173108fabae7111e03bf/src/ethereum_spec_tools/sync.py#L312
 - https://github.com/ethereum/execution-specs/blob/8e8379de0d61b2b76265173108fabae7111e03bf/src/ethereum/frontier/trie.py#L52

### PR DESCRIPTION
**Pull request by gurukamath**
### What was wrong?

Closes #393 

### How was it fixed?
Replaced uncle with ommer

### CODE REVIEW

**Review by SamWilsn — CHANGES_REQUESTED** [review]
The JSON files and the code that loads them needs to stay "uncle", just so we maintain compatibility with other tooling. I think everything else looks good!

**Comment by gurukamath** [comment]
@SamWilsn 
Have restored the JSON files as well as the references to wherever the data gets loaded from them
E.g - hex_to_bytes32(json["sha3Uncles"]) in src/ethereum_spec_tools/sync.py

Have presumed that the `fetch_uncles` function becomes `fetch_ommers` though. Do let me know if this is not the case.

**Comment by SamWilsn** [comment]
Hey @gurukamath!

I took the liberty of applying a few changes to your branch to clean it up and get everything working, I hope that's okay.

The changes were:

 - We use `git rebase` on feature branches (to help keep the commit history nice and clean), so I shuffled your commits around a bit to remove the merge.
 - Switch back to `uncle` for a few places in the sync tool, to conform to the API endpoints (you can find them [here](https://eth.wiki/json-rpc/API#json-rpc-methods) for future reference.)

Thanks so much for taking care of this issue :purple_heart:

**Comment by gurukamath** [comment]
@SamWilsn Thanks for the feedback and the suggestions. 
I am fine with any changes that you see as fit. If I understand you right, the changes you made close the issue and I need to take no further action here.

**Comment by SamWilsn** [comment]
That's correct! I was just waiting for the tests to pass before merging. Thanks again!

**Pull request merged**
